name: data-prep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - gdal
  - hyp3_sdk
  - numpy
  - pandas
  - dask
  - pip:
    - rasterio
    - certifi
    - asf_hyp3
    - requests
    - boto3